### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy-tracks#5]
@mingun do you think this is interesting?  Would you mind taking a look?

**Comment by Mingun** [comment]
I've never thinking about making such visualizations for my grammars, maybe because they are quite big and I doubt that visualization would be looks great because of this. Thanks for invitation -- I'll know that such a tool exists, although I'll do not follow its development, at least until I need it.

I've looked at all commits and find only a small typo here and in the Readme (`ouptut -> output`):
https://github.com/peggyjs/peggy-tracks/blob/6f7e13b46960f7dfde3988c67793337b18e05d00/bin/peggy-tracks.js#L14

Also I was think that you could add options for SVG generator if they exist (I think, you can able to specify colours, background opacity, maybe line styles).

You also can add a special outline for nodes that have an action, or add an action as a separate node to the diagram (especially because you add a code from predicates). I think that option for hiding user code also could be useful (just use nodes like `{...}` to show that node exists but without actual content, maybe with hyperlink to content)

**Comment by hildjj** [comment]
All good comments, thanks.  I think I've added some bits that will help.  I'm going to do a release and see if anyone cares. :)
